### ISSUE TITLE
Modularize xtf

### ISSUE THREAD

**Issue by Crumby** [xtf-cz/xtf#26]
At this point, XTF is created by one project only. In order to simplify number of dependencies and project maintainability is should be divided in several specialized modules.

Suggested modules:
- Utilities - common group of base utilities targeted to work with OpenShift
- JUnit 4 - annotations, suites, rules specialized for running tests against OpenShift environment with JUnit 4
- JUnit 5 - annotations, extensions specialized for running tests against OpenShift environment with JUnit 5
- Application Model - structures and objects for creating and deploying concrete applications on Openshift

@dsimansk From release point of view, do you think better would be multimodule project. Or several separeted projects at xtf-cz?

@maschmid Do you have any other suggestions?

**Comment by dsimansk** [comment]
@Crumby imho we should stick with one parent pom and multi-modules to keep the dependency version under one hood. On the other hand there's a question, if we would like to release all module with same version or keep them updated separately. E.g. JUnit 4 module is probably not going to see a lot of changes.

**Comment by Crumby** [comment]
Done.
