### ISSUE TITLE
Logic for finding OC client does not work on OCP 4.1

### ISSUE THREAD

**Issue by mchoma** [xtf-cz/xtf#265]
1. Seems location for OCP 4.1 clients changed to 
`https://mirror.openshift.com/pub/openshift-v4/clients/oc`. Xtf use hardcoded url [1]

2. Seems OCP 4.1  url for finding out version changed from `/version/openshift` to `/version` . Xtf use hardcoded [2]

Xtf should somehow deal with that. Either have different logic for OCP 3.x and OCP 4.x or just externalize these parameters with `-Dxtf.*` properties.

```
curl -k https://api.eap-qe-mnovak2-ocp41.eap-qe-mnovak2-ocp41.fw.rhcloud.com:6443/version
{
  "major": "1",
  "minor": "13+",
  "gitVersion": "v1.13.4+81fc896",
  "gitCommit": "81fc896",
  "gitTreeState": "clean",
  "buildDate": "2019-04-21T23:18:54Z",
  "goVersion": "go1.11.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

[1] https://github.com/xtf-cz/xtf/blob/e7f024ff66245784eaca4f053544c6a11e360b05/core/src/main/java/cz/xtf/core/openshift/OpenShifts.java#L27
[2] https://github.com/xtf-cz/xtf/blob/e7f024ff66245784eaca4f053544c6a11e360b05/core/src/main/java/cz/xtf/core/openshift/OpenShifts.java#L95

**Comment by Crumby** [comment]
For short term, you can use OpenShift [version](https://github.com/xtf-cz/xtf/blob/e7f024ff66245784eaca4f053544c6a11e360b05/core/src/main/java/cz/xtf/core/config/OpenShiftConfig.java#L6) property to set version to download within v3 clients (eg.: 4.0.22).

For long term I agree that we will need to update this mechanics.

**Comment by mchoma** [comment]
yeah, that is how we workaround right now

**Comment by jbliznak** [comment]
Some time passed and now recent 4.x clients are no longer accessible within `https://mirror.openshift.com/pub/openshift-v3/clients/`.
Instead they seem to be at `https://mirror.openshift.com/pub/openshift-v4/clients/oc/`

**Comment by mchoma** [comment]
There is also another option: On OCP 4.3 console this seems to be bundled in OCP installation

Question mark in right corner > Command Line Tools > Download oc for Linux for x86_64

E.g. https://downloads-openshift-console.apps.ocp4-cluster-6bdc3.ocp4-cluster-6bdc3.fw.rhcloud.com/amd64/linux/oc.tar

I mentioning here just for completness I prefer https://mirror.openshift.com/pub/openshift-v4/clients/oc/ way.

**Comment by llowinge** [comment]
@mchoma I've tried to implement downloading of oc from the downloads url you suggested.
