### ISSUE TITLE
Allow testsuite to pull images from secured repo e.g. `registry.redhat.io`

### ISSUE THREAD

**Issue by mchoma** [xtf-cz/xtf#283]
This seemed to be in https://github.com/xtf-cz/xtf/pull/153/files however was removed by https://github.com/xtf-cz/xtf/commit/dafcd8def33d039256e88e431befac4acb412fa5 .

**Comment by dsimansk** [comment]
@maschmid @Crumby 
Would be a `ProjectCreator` [listener](https://github.com/xtf-cz/xtf/blob/master/junit5/src/main/java/cz/xtf/junit5/listeners/ProjectCreator.java) a good place to migrate the former code that created registry secret and linked it to SAs? Wdyt? Or a separate is better alternative?

AFAIK @rvais is currently looking into providing a solution based on the previous impl.

**Comment by mnovak1** [comment]
hi guys, did you manage to deal with it ro it's still unresolved?

**Comment by rvais** [comment]
I have working implementation in ProjectCreator class. However I still wait for the reply in this thread whether or not I should create PR.

**Comment by Crumby** [comment]
@dsimansk @rvais Yes, ProjectCreator is a good place where this feature should be present. But it should also work in a reasonable way for [BuildManager](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/bm/BuildManager.java#L15)

**Comment by rvais** [comment]
I will put the code to BuildManager as well and create the PR ...

**Comment by Crumby** [comment]
Is this still needed? Pulling from secured repositories works out of the box with OpenShift4.

**Comment by mchoma** [comment]
@Crumby  how do you mean? How would you make xtf to work with image from [1]? 

Anyway, we still test on OCP 3.11 and will for a long. 

[1] https://access.redhat.com/containers/?tab=images&get-method=red-hat-login#/registry.access.redhat.com/jboss-eap-7-tech-preview/eap-cd-openshift-rhel8

**Comment by Crumby** [comment]
@mchoma Every OpenShift 4 requires pull secret passed during installation. That pull secret is than used for downloading images from secured repository.
