### ISSUE TITLE
Support multiple instances of OpenshiftUtil

### ISSUE THREAD

**Issue by sutaakar** [xtf-cz/xtf#29]
Currently OpenshiftUtil is implemented as a singleton. OpenshiftUtil is namespace aware, this is specified in OpenShiftContext. When user wants to change a namespace of OpenshiftUtil then he must set appropriate OpenShiftContext. During this context setup the underlying OpenShift client is closed.

This is the major limitation for running parallel tests in separated projects(namespaces). In such case there is a need to configure several projects and their resources at once. This is impossible with current singleton approach.

A possibility to address this limitation would be to allow using more instances of OpenshiftUtil class at once. It can be achieved for example by allowing to create specific OpenshiftUtil instance for any project.

**Comment by Crumby** [comment]
Hey @sutaakar, I have re-implemented OpenShiftUtil and marked old util as deprecated. All the functionality should stay. See [pull request](https://github.com/xtf-cz/xtf/pull/32) for more info and if current implementation suites your needs.

**Comment by Crumby** [comment]
The reasons for re-implementing whole class are to simplify the utility. Also note that other utils (like BuildManager or WaitingUtil) still depend on original Openshift Util. This is so we have time to migrate without braking our test suites. This utils will move to instantiatible OpenShiftUtil class (note the uppercase S) in near future.

**Comment by sutaakar** [comment]
@Crumby The new implementation looks good, thank you.
