### ISSUE TITLE
[bug] Openshift waiter "hasBuildCompleted" with buildConfigName is failing if build is not yet existing ...

### ISSUE THREAD

**Issue by radtriste** [xtf-cz/xtf#305]
I came to the case where I create the build via the command line "oc start-build ..." and then try to wait for the build to be completed, using this method in OpenshiftWaiter class:

```java
public Waiter hasBuildCompleted(String buildConfigName) {
	return hasBuildCompleted(openShift.getLatestBuild(buildConfigName));
}
```

This is calling:

```java
public Waiter hasBuildCompleted(Build build) {
	Supplier<String> supplier = () -> openShift.getBuild(build.getMetadata().getName()).getStatus().getPhase();
	String reason = "Waiting for completion of build " + build.getMetadata().getName();

	return new SupplierWaiter<>(supplier, "Complete"::equals, "Failed"::equals, TimeUnit.MINUTES, 10, reason).logPoint(Waiter.LogPoint.BOTH).interval(5_000);
}
```

There I can a `NullPointerException` because there is no latest build existing and thus, the build sent to this method is null.

I say we shall wait for the latest build to exist (or check it is the corect latest build ...)

**Comment by mchoma** [comment]
Can you use `OpenShiftWaiters.isLatestBuildPresent()` ?

**Comment by radtriste** [comment]
This one is indeed useful. I missed it ...

But still, from `OpenShiftWaiters.hasBuildCompleted(String buildConfigName)`, I would expect it is waiting that the build is created before getting it and waiting for it...

**Comment by radtriste** [comment]
I can make a quick PR for that if needed.
