### ISSUE TITLE
Relax CRD clean in case CRD is not installed

### ISSUE THREAD

**Issue by pkremens** [xtf-cz/xtf#312]
https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShift.java#L979
```
	public Waiter clean() {
	for (CustomResourceDefinitionContextProvider crdContextProvider : OpenShift.getCRDContextProviders()) {
			customResource(crdContextProvider.getContext()).delete(getNamespace());
	}
```
We install the operator CRD during the test execution, however the cleanup blows in case that CRD in not installed on cluster yet (e.g. first run on a clean cluster). We'd need relax this part a little bit so it doesn't fail in case that CRD is not installed yet.

**Comment by pkremens** [comment]
Or at least to have some other way to control this - sorry for vague description, I'm in pre-PTO time press, I'll add more details once I'm back.

**Comment by pkremens** [comment]
I'm getting back on this one. This is what I get at the moment (0.14-20190924.141535-5)
```
io.fabric8.kubernetes.client.KubernetesClientException: Error while performing the call to https://192.168.130.11:6443/apis/wildfly.org/v1alpha1/namespaces/pkremens-namespace/wildflyservers/. Response code: 403
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:230)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.delete(RawCustomResourceOperationsImpl.java:154)
	at cz.xtf.core.openshift.OpenShift.clean(OpenShift.java:985)
```

**Comment by Crumby** [comment]
Yeah, the `clean()` actually expects that CRD is already installed on the cluster before running the tests. But we can't ruin anything putting it into try/catch block. Will you create a PR with the fix?

**Comment by pkremens** [comment]
Sure, I'll look into it and let you know once I have something (ultimately I'll fall back to try/catch in case I won't be able to find some more intelligent solution).

**Comment by pkremens** [comment]
I also get this one in case that CRD is installed, but no instance of it is running.
```
io.fabric8.kubernetes.client.KubernetesClientException: Error while performing the call to https://192.168.130.11:6443/apis/wildfly.org/v1alpha1/namespaces/pkremens-namespace/wildflyservers/. Response code: 403
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:230)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.delete(RawCustomResourceOperationsImpl.java:154)
	at cz.xtf.core.openshift.OpenShift.clean(OpenShift.java:999)
```
I'll look into this as well, just fyi...
