### ISSUE TITLE
Add log level to Waiter interface (enhancement)

### ISSUE THREAD

**Issue by pkremens** [xtf-cz/xtf#316]
These would come handy:
```
new SimpleWaiter(() -> isConditionMet(), "Wait for condition to be met.", Level.DEBUG)
	.interval(100L)
	.waitFor();
```

https://stackoverflow.com/a/3831939

**Comment by dsimansk** [comment]
IMO this is great idea. @pkremens would you like to implement it? :)

**Comment by pkremens** [comment]
I'd really like to :), but I have no capacity to do it at the moment. I'll keep that one in my personal backlog and once I clean a table a little bit, I can look into it (no promises here). Nonetheless in case someone wants to take on it, it's free to be taken ;).
