### ISSUE TITLE
0.14-SNAPSHOT clean() deleting deployment config takes minute

### ISSUE THREAD

**Issue by mchoma** [xtf-cz/xtf#320]
![Screenshot from 2019-10-14 09-19-53](https://user-images.githubusercontent.com/10402702/66734541-cf622700-ee63-11e9-85b4-4b90440ceaea.png)

With xtf 12 clean() was 6 seconds
![Screenshot from 2019-10-14 08-31-15](https://user-images.githubusercontent.com/10402702/66732664-17318000-ee5d-11e9-9b9b-a517b751ebd0.png)

**Comment by mchoma** [comment]
@dsimansk any thoughts? ^

**Comment by dsimansk** [comment]
I assume the `wait...` method that takes ~ 1 min is [waitForObservedGeneration](https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java#L152).
That method previously took 100 ms, if I read the graph correctly. 

I'd suggest to open a new issue in fabric8's repo and follow up with them. Those are very good data to actually pin point what's wrong.

**Comment by mchoma** [comment]
@dsimansk  I have updated the screenshot, it is method waitForObservedGeneration()

**Comment by mchoma** [comment]
@dsimansk I have created https://github.com/fabric8io/kubernetes-client/issues/1808, but is there chance this performance lost is caused by order of objects to be deleted or delete parameters xtf use?

**Comment by dsimansk** [comment]
Thanks.
We started to mess with cascading param etc. after client upgrade. I'm pretty sure order wasn't changed though.

**Comment by dsimansk** [comment]
@mchoma
Based on [this fix](https://github.com/fabric8io/kubernetes-client/pull/1807) from release notes of `4.6.1`. I've tried to revert clean to former impl prior [PR#289](https://github.com/xtf-cz/xtf/pull/289) that called `delete()` method on list of resources. Surprisingly the execution time of whole delete block is ~7 s compared to ~70 s on current implementation.

**Comment by mchoma** [comment]
Interesting, can you add you findings on https://github.com/fabric8io/kubernetes-client/issues/1808. 

Do you currently see solution to have `clean()` not causing `WaiterException` and not have poor performance?

This is blocking our upgrade to newer xtf version and is getting urgent.

**Comment by dsimansk** [comment]
@mchoma @Crumby 
I've tested 2 different testsuites with 0.14-SNAPSHOT and recent (possible) fix. There were no waiting exception through the run and execution time was reduced back to "expected" value. If possible, please try it out in your suites as well.

**Comment by mchoma** [comment]
I am running our testsuite with 0.14-SNAPSHOT. I will let you know the result.

**Comment by mchoma** [comment]
I can confirm we are back to origin testsuite run time - ~ 4:30 h

**Comment by mchoma** [comment]
@dsimansk Could we have release with that change in place? Running our testsuite we do not see WaiterException: Cleaning project anymore and performance is ~ same.

**Comment by dsimansk** [comment]
Sure, that was my plan also. I'd like to get https://github.com/xtf-cz/xtf/pull/322 merged and cut the release afterwards.

**Comment by dsimansk** [comment]
Resolved in #321 and fix present in version `0.14`.
