### ISSUE TITLE
Remove workaround for "Use V1 API for templates with new kubernetes client versions"

### ISSUE THREAD

**Issue by mnovak1** [xtf-cz/xtf#380]

**Comment by mchoma** [comment]
https://github.com/fabric8io/kubernetes-client/issues/2373 was fixed, so I believe workaround in xtf is not necessary anymore. Need to be tested

**Comment by mnovak1** [comment]
Once new version of kubernetes-client will be released, we'll need to remove workaround made in:
https://github.com/xtf-cz/xtf/pull/374/files 

as it will be no longer needed.

**Comment by mnovak1** [comment]
Testing remove of workaround with latest snapshot - https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-openshift-product-face/

**Comment by mchoma** [comment]
Can we revisit this? It is doing problem in CVP environment where we do not have permission `get resource clusterversions`.

This is new now as we started to test on OCP 4 cluster in CVP environment.

**Comment by mnovak1** [comment]
Unfortunately I don't have capacity to deal with it. Thus unassigning from the issue.

**Comment by mchoma** [comment]
For reference fix was already prepared here https://github.com/mnovak1/xtf/commit/2698fe953e1376c21d20c73d5cadcf918a1f2204

**Comment by mchoma** [comment]
I can't put asignee, but @vsalbaba should have a look.

**Comment by mnovak1** [comment]
Done, closing.
