### ISSUE TITLE
Openshift.clean() gets stuck on OCP4.7

### ISSUE THREAD

**Issue by mocenas** [xtf-cz/xtf#406]
On OCP4.7, on every instance I've encountered. There is a configmap `kube-root-ca.crt` in every newly created namespace. Also this configmap can't be deleted. When I try to delete it, it won't be deleted (or possibly it is immediately created again?). 
This causes cleaning command `openshift.clean().waitFor();` to stuck, because configmaps in namespace will never be empty.
I'm not sure if this is bug or some new feature. I filed an [openshift issue](https://bugzilla.redhat.com/show_bug.cgi?id=1916688). Possibly this will require a change to cleanup method.

**Comment by mnovak1** [comment]
Based on bugzilla this is a feature - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#introducing-rootcaconfigmap

**Comment by mocenas** [comment]
Workaround is to mark the configMap with xtf.cz/keep label:
`oc label configmap kube-root-ca.crt xtf.cz/keep=true`

**Comment by Crumby** [comment]
@mnovak1 @mocenas #409 Fixes the issue
