### ISSUE TITLE
bintray maven repo is going down, new public repo needed for XTF releases

### ISSUE THREAD

**Issue by mnovak1** [xtf-cz/xtf#423]
As Bintray is going down [1], new maven repository is needed for XTF releases. Suggestion is to use:
```
	<repository>
            <id>oss-jfrog-release</id>
            <name>oss-jfrog-artifactory-release</name>
            <url>https://oss.jfrog.org/artifactory/oss-release-local</url>
        </repository>
```
but from the announcement [1] is not clear whether is going down as well. 

@dsimansk do you have any more info?

[1] https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by mcarlett** [comment]
Another alternative can be using [GitHub Packages](https://github.com/features/packages)

**Comment by mnovak1** [comment]
To avoid changing/adding another `<repository>` in consuming projects, Maven central would be ideal option. However PGP will be needed.

**Comment by mnovak1** [comment]
Thanks to help from @mcarlett new releases will be deployed to https://repository.jboss.org/nexus/content/groups/public/

Distribution management will change to:
```    
  <distributionManagement>
        <repository>
            <id>jboss-releases-repository</id>
            <name>JBoss Releases Repository</name>
            <url>https://repository.jboss.org/nexus/service/local/staging/deploy/maven2</url>
        </repository>
        <snapshotRepository>
            <id>jboss-snapshots-repository</id>
            <name>JBoss Snapshots Repository</name>
            <url>https://repository.jboss.org/nexus/content/repositories/snapshots</url>
        </snapshotRepository>
    </distributionManagement>
```

Sync for XTF will be configured between https://repository.jboss.org/nexus/content/groups/public/cz/xtf and Maven Central. This means that for getting new releases of XTF no special config (no new `<repository>`) should be required. 

I've already re-deployed XTF 0.21 into https://repository.jboss.org/nexus/content/groups/public/ .

However if someone wants to consume snaphots then new snapshot repository must be configured in `pom.xml`:
```
<repositories>       
       <repository>
            <id>jboss-snapshots-repository</id>
            <name>JBoss Snapshots Repository</name>
            <url>https://repository.jboss.org/nexus/content/repositories/snapshots</url>
        </repository>
</repositories>
```

**Comment by mnovak1** [comment]
XTF bits are now on Maven Central. 

Note that only XTF 0.21 was deployed there, in case other releases are needed then let me know.
