### ISSUE TITLE
Maven version update to 3.6

### ISSUE THREAD

**Issue by vsalbaba** [xtf-cz/xtf#425]
With maven version 3.5 reaching EOL (retired Oct 2020 - see https://access.redhat.com/support/policy/updates/rhscl-rhel7) change to version 3.6 is inevitable. However, version 3.5 is hardcoded in `ImageContent#mavenVersion()`

https://github.com/xtf-cz/xtf/blob/613f98808c608ef16fdee289f19aef0cc4682bdf/test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageContent.java#L149

This works as designed on `EAP 7.4.0.GA rhel7`

The created script will NOT fail even though `enable` script is not present in `/opt/rh/rh-maven35/`. On systems with system-provided maven (tested on image `EAP 7.4.0.GA rhel8`), it will lead to confusing results, such as:
``` bash
sh-4.4$ bash -c /tmp/maven-version.sh 
/tmp/maven-version.sh: line 1: /opt/rh/rh-maven35/enable: No such file or directory
Apache Maven 3.6.2 (Red Hat 3.6.2-5)
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-4.el8_3.x86_64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "5.10.25-linuxkit", arch: "amd64", family: "unix"
```

Note that enabling maven 3.5 failed, but maven version 3.6 is already present on the system, therefore result of `mavenVersion()` would be 3.6.2.

This would of course fail on system without system-provided maven or maven enable script in different location, ie. `/opt/rh/rh-maven36/enable`

I would suggest creating a new configuration option for path to maven enable script, defaulting to `/opt/rh/rh-maven35/enable` and not doing any init if option is set to empty.

**Comment by mnovak1** [comment]
@vsalbaba i think this can be closed, right?

**Comment by simkam** [comment]
@vsalbaba see question above?
