### ISSUE TITLE
Update openshift client to latest 5.x

### ISSUE THREAD

**Issue by simkam** [xtf-cz/xtf#427]
There are some breaking changes, but it shouldn't be complicated to deal with them. See [CHANGELOG.md](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) for details.

**Comment by simkam** [comment]
We should consider bumping XTF major version due to those breaking changes.

**Comment by simkam** [comment]
Another reason for update is support for [mountTrustedCA](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model-generator/openshift-model/src/generated/java/io/fabric8/openshift/api/model/BuildConfigSpec.java#L37) in Build and BuildConfig allowing injection of custom CAs to builds.

**Comment by jstourac** [comment]
JFTR - tentative proposal https://github.com/jstourac/xtf/commit/5fa61c9cefa02b06d2689bb2fdcc7f658498ba27
