### ISSUE TITLE
OpenShiftWaiters is using hardcoded timeouts

### ISSUE THREAD

**Issue by fabiobrz** [xtf-cz/xtf#438]
Looking at e.g. https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java#L61 (and other locations) an hardcoded value of 10 mins is used for the returned `Waiter`. 

Is there a reason for doing so instead of using e.g.: `WaitingConfig.timeout()` as it's done at https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java#L128 ?

We've found ourselves forced to implement such a tiny variation locally and this could be fine but I am wondering what the added value of the original (with hardcoded timeout) is in such a case.

If there is consensus on fixing the reported methods I can provide a PR.

CC  @mchoma @mnovak1 @simkam

**Comment by mchoma** [comment]
Your suggestion make sense to me.
