### ISSUE TITLE
review logic getting OCP version

### ISSUE THREAD

**Issue by simkam** [xtf-cz/xtf#456]
There are multiple options to detect OCP versions

- [configure it manually](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/config/OpenShiftConfig.java#L6)
- [get it from cluster](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShifts.java#L248) (if not configured)

[getVersion](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShifts.java#L248) method always calls cluster API, it should be cached on class initialization or on the first call. 

Currently, it is also [prone to NPEs](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShifts.java#L294) => NPE when version not configured manually

**Comment by mchoma** [comment]
IIRC historically there was manual configuration first, then we added logic to get from cluster. I think now ideally it should look like `if version is not configured manually search for version from cluster`

> prone to NPEs => NPE when version not configured manually
That mean this is bug and should be fixed to comply to what is written above.

> getVersion method always calls cluster API, it should be cached on class initialization or on the first call.
+1

**Comment by mnovak1** [comment]
Yep, calling cluster for every getVersion() call this is ineffective. +1 for this issue.
