### ISSUE TITLE
Unable to delete role binding via cleaning process with xtf 0.24 & OCP 4.9

### ISSUE THREAD

**Issue by KTsag** [xtf-cz/xtf#467]
When using xtf 0.24 with ocp 4.9 in jws operator test suite the project is unable to clean up a role binding and throws time out exception. cz.xtf.core.waiting.WaiterException: Cleaning project. Contrariwise, with xtf 0.23 cleaning process in cluster with ocp 4.9 is working fine.

**Comment by mnovak1** [comment]
Following roleBinding cannot be removed: ```RoleBinding@137 "RoleBinding(apiVersion=rbac.authorization.k8s.io/v1, kind=RoleBinding, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=2021-11-25T12:19:05Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels=null, managedFields=[], name=jws-operator.v1.2.0, namespace=ktsagara-tests, ownerReferences=[OwnerReference(apiVersion=operators.coreos.com/v2, blockOwnerDeletion=false, controller=true, kind=OperatorCondition, name=jws-operator.v1.2.0, uid=13abc7ea-bc7e-49fe-a648-959e81bd1405, additionalProperties={})], resourceVersion=414636, selfLink=null, uid=88097dbc-eba8-45fe-aaf7-6d436b6eeb1b, additionalProperties={}), roleRef=RoleRef(apiGroup=rbac.authorization.k8s.io, kind=Role, name=jws-operator.v1.2.0, additionalProperties={}), subjects=[Subject(apiGroup=null, kind=ServiceAccount, name=jws-operator, namespace=null, additionalProperties={})], additionalProperties={})"```

**Comment by mnovak1** [comment]
@KTsag was able to figure it out. The given role binding was missing `cz.xtf/keep=true` label. Closing.
