### ISSUE TITLE
OCP 3.11 generetad mirror URL is not found 

### ISSUE THREAD

**Issue by mcarlett** [xtf-cz/xtf#472]
Using OCP 3.11, during the download of the oc client, the mirror URL generated is https://mirror.openshift.com/pub/openshift-v3/clients/3.11.521/linux/ but it doesn't exists, while https://mirror.openshift.com/pub/openshift-v3/clients/3.11.521-1/linux/ exists.

**Comment by mnovak1** [comment]
@mcarlett afair this one is resolved, right?

**Comment by mcarlett** [comment]
yes @mnovak1 , sorry, I forgot to close it

**Comment by mnovak1** [comment]
Thanks, closing.
