### ISSUE TITLE
[Question] - Should XTF test itself?

### ISSUE THREAD

**Issue by fabiobrz** [xtf-cz/xtf#476]
The kubernetes-client project, which XTF is based on, provides a [functionality](https://github.com/fabric8io/kubernetes-client#mocking-kubernetes) to mock k8s and to test the client itself.

Lately it has been discussed how XTF is also tested by executing test suites that depend on it, hence the question: should XTF do the same of kubernetes-slient and test itself? 
BTW - the kubernetes-client project provides an [OpenShiftServer](https://github.com/fabric8io/kubernetes-client/blob/master/openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftServer.java) class that mocks an OpenShift cluster and maybe that could be used for this specific case.

WDYT @mnovak1, @simkam, @mchoma?

**Comment by mnovak1** [comment]
@fabiobrz there is long term goal to provide test suite for XTF - it's tracked under https://github.com/xtf-cz/xtf/issues/325 . Can we continuew the discussion there?

**Comment by fabiobrz** [comment]
> @fabiobrz there is long term goal to provide test suite for XTF - it's tracked under #325 . Can we continuew the discussion there?

Hi @mnovak1 - thanks for pointing me there and sorry about duplication! 

Sure we can discuss there, I'll close the issue.
