### ISSUE TITLE
@SkipFor annotation generates client error if namespace doesn't exists

### ISSUE THREAD

**Issue by mcarlett** [xtf-cz/xtf#488]
If I use `@SkipFor` annotation to match the image metadata, a temporary image stream will be created in the configured namespace, but, if the namespace is not already existing, there will be an error like `Namespace xxxx not found`, exiting the application.

**Comment by mnovak1** [comment]
Ideal would be not need to import image into Openshift to get the metadata.

**Comment by mnovak1** [comment]
However I'm not sure if it's possible.

**Comment by mcarlett** [comment]
I think it is possible using [Skopeo](https://github.com/containers/skopeo) but it is required to be installed (or maybe downloaded/managed as already done with OC binary)

**Comment by mnovak1** [comment]
Major limitation of Skopeo and other tools is that it must run inside Openshift as it might have configured pull secrets for remote docker registry. Basically it must be called from Openshift. I think the current way is the only one which will 100% work. However I've added a comment to PR https://github.com/xtf-cz/xtf/pull/489 to improve it.

**Comment by simkam** [comment]
I'm not sure about this. Isn't it enough to have `cz.xtf.junit5.listeners.ProjectCreator` in `META-INF/services/org.junit.platform.launcher.TestExecutionListener`. There are more extensions that expect `ProjectCreater` loaded first.

**Comment by mcarlett** [comment]
> I'm not sure about this. Isn't it enough to have `cz.xtf.junit5.listeners.ProjectCreator` in `META-INF/services/org.junit.platform.launcher.TestExecutionListener`? There are more extensions that expect `ProjectCreater` loaded first.

yes it would be a nice and clean solution, but if I use an existing test suite that already manages the project lifecycle could be a little bit tricky having 2 different ways to manage the project creation, thanks for the tip!
