### ISSUE TITLE
Add configuration for connection waiting time

### ISSUE THREAD

**Issue by KatyT123** [xtf-cz/xtf#498]
Our Jenkins fails occasionally to download the oc binary with error:
Caused by: java.lang.IllegalStateException: Failed to download and extract oc binary from https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.10.21/openshift-client-linux.tar.gz

So because we don't have such issue on local computer i believe the problem is caused by timeout connection exception which is set to 20s by default. So could you please add some configuration in order to be able to set the connection timeout?

**Comment by simkam** [comment]
can you please paste error output of `IllegalStateException`?

**Comment by simkam** [comment]
and what version of XTF do you use?

**Comment by KatyT123** [comment]
It seems that connecting to the server requires **something less than a second**, hence for this reason, **please close the issu**e since there is no need to increase waiting time out with more than 20 sec.

[hudson@psi-rhel-8-x86-64-no-retention-time-with-tools-1761 ~]$ date && wget -c https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.9.0/openshift-install-linux-4.9.0.tar.gz && date
Wed Jul 27 03:24:56 EDT 2022
--2022-07-27 03:24:56--  https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.9.0/openshift-install-linux-4.9.0.tar.gz
Resolving [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))... 2600:9000:2305:4a00:17:3d36:19c0:93a1, 2600:9000:2305:4400:17:3d36:19c0:93a1, 2600:9000:2305:600:17:3d36:19c0:93a1, ...
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:4a00:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:4400:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:600:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:c600:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:1e00:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:aa00:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:6600:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|2600:9000:2305:4200:17:3d36:19c0:93a1|:443... failed: No route to host.
Connecting to [mirror.openshift.com](http://mirror.openshift.com/) ([mirror.openshift.com](http://mirror.openshift.com/))|18.67.76.76|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable
