### ISSUE TITLE
XTF does not support custom Kubeconfig with cert/key file for OpenShiftBinary

### ISSUE THREAD

**Issue by mnovak1** [xtf-cz/xtf#527]
XTF allows to set custom kubeconfig file for https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShiftBinaryManager.java#L58 using `xtf.openshift.master.kubeconfig` and `xtf.openshift.admin.kubeconfig` properties. 

Problem is that if there is for example custom kubeconfig file `/some-path/config` defined with cert/key for user like:
```
users:
- name: xpaasqe
user:
  client-certificate: */client.crt
  client-key: */client.key
```

then those cert/key files are not copied to config directory together with `/some-path/config` file (XTF makes copy of this file usually in `/tmp/oc/` directory and renames it to `oc.config`) and thus later authentication fails. 

Possible solutions are:

- Introduce new properties for setting path cert/key which would copied as well: 
```
xtf.openshift.master.key
xtf.openshift.master.cert
xtf.openshift.admin.key
xtf.openshift.admin.cert
```

- Introduce new properties for setting path to kubeconfig directory which content would be copied (it would be exected that file named `config` is kubeconfig file): 
```
xtf.openshift.master.kubeconfig.dir
xtf.openshift.admin.kubeconfig.dir
```

- Suggest any other option ;-)

**Comment by mnovak1** [comment]
@mchoma @jbliznak fyi

**Comment by smongiar** [comment]
I would like to proceed with the creation of 4 more properties:
```
xtf.openshift.admin.kubeconfig.key
xtf.openshift.admin.kubeconfig.cert
xtf.openshift.master.kubeconfig.key
xtf.openshift.master.kubeconfig.cert
```
 as discussed in #526 in order to maintain the separation between admin/master properties

**Comment by jbliznak** [comment]
TBH I am more keen to the "copy config directory" approach just to avoid future reiteration of similar problem with some other referenced file. There can still be separate dirs prepare for each user if needed.

Bun in case we go with properties only, is `xtf.openshift.admin.kubeconfig.key` just to have a path to copy and it is up to the use to have content of config file synced with the name of this file or will the XTF also take care of this?

**Comment by simkam** [comment]
@smongiar I wonder, how do you create kubeconfig with key and cert in separate files? Can't just create kubeconfig with embedded key and cert? No changes in XTF would be needed?

**Comment by smongiar** [comment]
@jbliznak

I faced the issue while I was using a `/home/user /.kube/config` not created by me. It was provided by our partner engineers for integration testing. So, you can imagine how important is to use separate certificates and keys. 

The starting point was a kubeconfig file like:
```
 users:
- name: admin/cds149rd042m87juef2g
  user:
    client-certificate: admin.pem
    client-key: admin-key.pem
```

Actually XTF framework copy this configuration to its own `oc.config` file. So, it expects that the two authorization files needed are placed in the same path of `oc.config` file. Morover we should sadly pay attention that `xtf.openshift.admin.kubeconfig.key` is properly valued with this logic.

@smikam

IMHO we shouldn't place limits on how XTF connects to the cluster. 
As mentioned, the kubeconfig file was provided to me, not created by me

**Comment by simkam** [comment]
hmm what about converting config into portable?

```
    --flatten=false:
        Flatten the resulting kubeconfig file into self-contained output (useful for creating portable kubeconfig
        files)
```

Running `oc config view --kubeconfig ${xtf.openshift.admin.kubeconfig} --flatten` and storing output to `ocConfigPath`

**Comment by smongiar** [comment]
> oc config view --kubeconfig ${xtf.openshift.admin.kubeconfig} --flatten

Can we do this directly in the XTF framework?

**Comment by simkam** [comment]
I think that something like 

```
OpenShiftBinary originalConfigBinary = new OpenShiftBinary(OpenShifts.getBinaryPath(), null);
String output = originalConfigBinary.execute("oc config view --kubeconfig " + kubeconfig + "--flatten");
...
``` 
should work, but I didn't try it.

**Comment by mnovak1** [comment]
> OpenShiftBinary originalConfigBinary = new OpenShiftBinary(OpenShifts.getBinaryPath(), null);
> String output = originalConfigBinary.execute("oc config view --kubeconfig " + kubeconfig + " --flatten");

I like it more than the other 2 options.

**Comment by mnovak1** [comment]
@smongiar Will you able to try ^ or do you want me to prepare something to test?

**Comment by mnovak1** [comment]
@smongiar Actaully I've just did it :-) could you try to test my branch: https://github.com/mnovak1/xtf/tree/all-in-one-kubeconfig

**Comment by smongiar** [comment]
@mnovak1 sorry for the late response, I will try it and let you know :) And thanks for your branch

**Comment by mnovak1** [comment]
Thanks, I've blindly coded it without try so it might need a few tweaks.

**Comment by smongiar** [comment]
@mnovak1 after execution of https://github.com/mnovak1/xtf/blob/1318369ed8a817ed1e2cf6ee87947d50ce656b0a/core/src/main/java/cz/xtf/core/openshift/OpenShiftBinaryManager.java#L67 the resulting `oc.config` is filled with the "null" value. I'm still investigating about the reasons

**Comment by smongiar** [comment]
@mnovak1 Ok, I fixed changing the execute parameters as `String[]` type:
`.execute("config", "view", "--kubeconfig", kubeconfig, "--flatten"))`

PR updated in https://github.com/xtf-cz/xtf/pull/526
