### ISSUE TITLE
subid image does not override id image in xtf properties

### ISSUE THREAD

**Issue by mchoma** [xtf-cz/xtf#571]
I have this configuration in our testsuite 

```
xtf.eap.image=registry.redhat.io/jboss-eap-8/eap8-openjdk17-builder-openshift-rhel8:latest
xtf.eap.wildfly-openjdk17.image=quay.io/wildfly/wildfly-s2i:latest-jdk17
```

Idea is to have default image for products and override wildfly image for specific value. Unfortunatelly it does not behave like that and value is not overriden.

I can workaround by specifying image in each subid section. But could image behave similar as all other properties?

I think solution can be simple as switching order of code here https://github.com/xtf-cz/xtf/blob/1daa976b2e32c0bc9fcdfda1ae947d37836c15fa/core/src/main/java/cz/xtf/core/image/Image.java#L21-L28. First try to get image from subid, e.g. `eap.wildfly-openjdk17` and once it is not there default to `eap`

**Comment by mnovak1** [comment]
I'm ok with this change. Current logic seems to be wrong.

**Comment by mchoma** [comment]
@dosu what do you think?

**Comment by mchoma** [comment]
@dosu any objection with linked pull request? Do you think it address original issue? Are test correctly testing touched code?

**Comment by mnovak1** [comment]
@dosu could you generate test case which would test functionality of `resolve` method in linked pull request?

**Comment by mchoma** [comment]
@dosu could you generate test for resolve method please?

**Comment by mchoma** [comment]
@mnovak1 Can you have a look ^ if there is something to incorporate from those proposals? :)
