### ISSUE TITLE
CLIUtils creates a new thread pool for every command and does not terminate a threads

### ISSUE THREAD

**Issue by kstekovi** [xtf-cz/xtf#581]
When is used `SimpleWaiter` together this OpenShift binary it create two threads for every check of current state of resource in the OpenShift.  So it can create hundreds of threads when it waits for start of a POD. Unfortunately these thread are never terminated. There are sleeping or waiting. 

![ThreadPool](https://github.com/user-attachments/assets/d12f6519-7221-4357-af38-4c9ba34b3728)

**Comment by simkam** [comment]
resolved by https://github.com/xtf-cz/xtf/pull/582
